_target_: aurmr_policy_models.agents.learned_agent.LearnedAgent
agent_name: learned_agent
version: 0


model: ${model}

# model:
#   _target_: aurmr_policy_models.models.basic_mlp.MLP
#   input_dim: 4
#   output_dim: 1