_target_: aurmr_policy_models.models.diffusion.diffusion.DiffusionModel
model_name: diffusion
predict_epsilon: True
denoised_clip_value: 1.0

# Sampling HPs
min_sampling_denoising_std: 0.1
randn_clip_value: 3
#
network_path: ${base_policy_path}

actor:
  _target_: aurmr_policy_models.models.diffusion.mlp_diffusion.DiffusionMLP
  time_dim: 16
  mlp_dims: [512, 512, 512]
  activation_type: ReLU
  residual_style: True
  cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
  horizon_steps: ${horizon_steps}
  action_dim: ${action_dim}
critic:
  _target_: aurmr_policy_models.models.common.critic.CriticObsAct
  action_dim: ${action_dim}
  action_steps: ${act_steps}
  cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
  mlp_dims: [256, 256, 256]
  activation_type: Mish
  residual_style: True
horizon_steps: ${horizon_steps}
obs_dim: ${obs_dim}
action_dim: ${action_dim}
denoising_steps: 100
device: 'cuda:0'
