_target_: aurmr_policy_models.models.diffusion.diffusion.DiffusionModel
model_name: diffusion
predict_epsilon: True
denoised_clip_value: 1.0
network_path: null
network:
  _target_: aurmr_policy_models.models.diffusion.mlp_diffusion.DiffusionMLP
  time_dim: 16
  mlp_dims: [512, 512, 512]
  activation_type: ReLU
  residual_style: True
  cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
  horizon_steps: ${horizon_steps}
  action_dim: ${action_dim}
horizon_steps: ${horizon_steps}
obs_dim: ${obs_dim}
action_dim: ${action_dim}
denoising_steps: 100
device: 'cuda:0'